stages:
  - build

variables:
  CARGO_TERM_COLOR: always

build-linux:
  stage: build
  image: rust:latest
  script:
    - rustup target add x86_64-unknown-linux-gnu
    - cargo build --release --target x86_64-unknown-linux-gnu
  artifacts:
    paths:
      - target/x86_64-unknown-linux-gnu/release/
    expire_in: 1 week

build-windows:
  stage: build
  image: rust:latest
  before_script:
    - apt-get update && apt-get install -y mingw-w64
  script:
    - rustup target add x86_64-pc-windows-gnu
    - cargo build --release --target x86_64-pc-windows-gnu
  artifacts:
    paths:
      - target/x86_64-pc-windows-gnu/release/
    expire_in: 1 week
